### ISSUE TITLE
The 1.3.6 released is fucked

### ISSUE THREAD

**Issue by blshkv** [arxsys/dff#23]
Subj! Excuse my French, but I can't find better words. 

First of all, it were no commits before Feb 14 and the release just come up from nowhere.

Next, the released tarball can't be even installed, it is missing modules/ui/cmake/docs components. These components are in a separate tree (fine!), but they have no releases (or badly outdated) so it is not clear which version should be used.

I managed to resolve all these, but dff does not start. There is no ```VERSION``` variable defined (used to be in ```dff/__init__```), /usr/bin/dff is calling ```from dff.ui.ui import Usage``` which does not exist and so on.

I just gave up at this stage.

**This is not the quality which you expect to trust for forensics investigations.**

**Comment by vertrex** [comment]
The project is currently stalled as we close the company who maintained and develop it . We need to find time to go back on the project, recreate our  dev./packaging env. , merge the pro version tree that will become open-source etc... we're only two person working on the project and now it's not a full time project for us. We have planned to work on it during the summer and release a stable version, that compile and is packageable, that will become the new master branch.
